# Generated by Django 3.2.4 on 2021-10-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='ApiKey',
            field=models.CharField(max_length=325, unique=True),
        ),
    ]
